homeassistant:
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_h
  longitude: !secret longitude_h
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 257
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml

  customize_domain: !include customize_domain.yaml 

http: !include http.yaml

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: !secret influxdburl

config:

influxdb: !include influxdb.yaml

custom_updater: !include custom_updater.yaml

#discovery:

#Od verze HA 0.84 musí být lovelace nastavený na mode yaml aby se načítal z yaml souboru.
lovelace:
  mode: yaml

hassio:

updater:

# MQTT
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_name
  password: !secret mqtt_pw
  discovery: true
  discovery_prefix: homeassistant

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation: !include conversation.yaml
dialogflow:

intent_script: !include_dir_merge_named intent_scripts/

scene: !include scenes.yaml

history: !include history.yaml

recorder: !include recorder.yaml

history_graph: !include history_graphs.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

shell_command: !include shell_commands.yaml

# Text to speech
tts: !include tts.yaml

# Google assistant
google_assistant:
  project_id: !secret gass_projectid
  api_key: !secret gass_api_key
  expose_by_default: false
  exposed_domains:
    - light
    - script
    - switch
    - scene
  entity_config: !include_dir_merge_named google_assistant/

ifttt:
  key: !secret ifttt_api

#iOS
ios: !include ios.yaml

# Cloud
# cloud: !include cloud.yaml
circadian_lighting:

mdpo:

#Počasí
weather: !include weather.yaml

homekit: !include homekit.yaml

notify: !include notifies.yaml

zone: !include zones.yaml   

## INPUTS ##
#input_text: !include inputs/input_text.yaml
input_number: !include inputs/input_number.yaml
input_select: !include inputs/input_select.yaml

## DEVICES ##
switch: !include devices/switches.yaml
media_player: !include devices/media_players.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
light: !include devices/lights.yaml
counter: !include devices/counters.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
